<?php

/**
 * Implements hook_views_data().
 */
function routes_list_views_data() {
  
  $data['router'] = [];
  $data['router']['table'] = [];
  // Base data.
  $data['router']['table']['group'] = t('Routes');
  $data['router']['table']['base'] = [
    'title' => t('Routes'),
    'help' => t('Core Routes'),
    'field' => 'router',
  ];
  // Fields
  $data['router']['name']['field'] = [
    'title' => ('Name'),
    'id' => 'standard',
    'field_name' => 'name',
    'help' => ('The route name.'),
    'property' => 'name',
    'click sortable' => TRUE,
  ];
  $data['router']['path']['field'] = [
    'title' => ('Path'),
    'id' => 'standard',
    'field_name' => 'path',
    'help' => ('The route path.'),
    'property' => 'path',
    'click sortable' => TRUE,
  ];
  // Filters
  $data['router']['name']['filter'] = [
    'id' => 'string',
    'title' => 'Name',
  ];
  $data['router']['path']['filter'] = [
    'id' => 'string',
    'title' => 'Path',
  ];
  // Sorts
  $data['router']['name']['sort'] = [
    'title' => 'Name',
    'field' => 'name',
  ];
  $data['router']['path']['sort'] = [
    'id' => 'standard',
    'title' => 'Path',
  ];

  return $data;
}
