services:
  php:
    # Use PHP 8.x with Apache; this syntax pulls in the latest version of PHP 8.
    #image: tugboatqa/php:8.1-apache
    image: tugboatqa/php:apache

    # Set this as the default service. This does a few things:
    #   1. Clones the git repository into the service container
    #   2. Exposes port 80 to the Tugboat HTTP proxy
    #   3. Routes requests to the preview URL to this service
    default: true

    # Wait until the mysql service is done building.
    depends:
      - mysql

    # A set of commands to run while building this service.
    commands:
      # Commands that set up the basic preview infrastructure.
      init:
        - echo "===== Apache/PHP Init ======"
        - alias ll='ls -la'
        - mysql --help | grep "Default options" -A 1

        # Link the document root to the expected path. This example links
        # /var/lib/tugboat/web to the docroot of the Apache server (/var/www/html).
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"

      update:
        - echo "===== Apache/PHP Update ====="

        # Import the database.
        - zcat project/database/performant-labs_dev.sql.gz | mysql -h mysql -utugboat -ptugboat tugboat

      # Only step that executes on new PR or tugboat builds from base previews.
      build:
        - echo "===== Apache/PHP Build ====="

        - # Use the tugboat-specific Drupal settings.
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.tugboat.php" "${DOCROOT}/sites/default/settings.local.php"

  mysql:
    #image: tugboatqa/mysql:8-debian
    image: tugboatqa/mysql

    commands:
      init:
        - echo '===== mySQL Service Init ======'

        # Increase the allowed packet size to 512MB.
        - mysql -e "SET GLOBAL max_allowed_packet=2147483648;"
        - mysql --help | grep "Default options" -A 1

        # Ensure this packet size persists even if MySQL restarts.
        - echo "max_allowed_packet=2147483648" >> /etc/mysql/tugboat.cnf
