name: 'Environment Indicator'
type: module
description: 'Adds a color indicator for the different environments.'
package: Development
core_version_requirement: '^9.3 || ^10 || ^11'
configure: environment_indicator.settings
