name: Environment indicator
type: module
description: Adds a color indicator for the different environments.
package: Development
core_version_requirement: ^9.3 || ^10 || ^11

scripts:
  - js/environment_indicator.js
  - js/color.js

stylesheets:
  all:
    - css/environment_indicator.css

configure: environment_indicator.settings
