<?php

/**
 * @file
 * The primary PHP file for the Performant_Labs theme.
 */

/**
 * Implements hook_preprocess_html().
 */
function performant_labs_preprocess_html(&$variables) {

  $current_path = \Drupal::service('path.current')->getPath();
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  $path_alias = ltrim($path_alias, '/');
  $variables['attributes']['class'][] = \Drupal\Component\Utility\Html::cleanCssIdentifier($path_alias). "-page";

}
