name: Add PR Comment

on:
  repository_dispatch:
    types: [add-pr-comment-command]  

jobs:
  add_comment:
    runs-on: ubuntu-latest
    # Do this only if the PR was created by dependabot
    if: github.event.client_payload.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Trigger the visual testing
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            /add-solo-comment
