name: "Auto Merge Dependabot Security Updates"

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies') && contains(github.event.pull_request.title, 'security update')
    
    steps:
    - name: Approve pull request
      run: |
        gh pr review --approve ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge pull request
      run: |
        gh pr merge --merge ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
