name: Command Dispatcher
on:
  issue_comment:
    types: [created]
jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.GH_PAT }}
        commands: update-package, add-solo-comment, call-child
