name: Command Dispatcher
on:
  issue_comment:
    types: [created]
jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.GH_PAT }}
        commands: run-a-task
        permission: none
        issue-type: both
