name: Run Cypress tests.
run-name: ${{ github.actor }} is running Cypress.
on: workflow_dispatch

env:
  php_version: '8.1'
  pantheon_site_name: 'performant-labs'
  pantheon_env: 'dev'

jobs:
  Deploy-to-Dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "For site $pantheon_site_name.$pantheon_env."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code.
        uses: actions/checkout@v3
        
      - name: Set up PHP.
        uses: shivammathur/setup-php@2.24.0
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          php-version: ${{ env.php_version }}
          
      - name: Checkout.
        uses: actions/checkout@v3
        
      - name: Set Composer cache directory.
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        
      - name: Cache Composer dependencies.
        uses: actions/cache@v3.2.4
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-    
            
      - name: Avoid GitHub rate limit for Composer.
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
        
      - name: Install Composer.
        run: composer install --optimize-autoloader --no-dev --prefer-dist --no-interaction --no-progress
                 
      - name: Rnn Cypress tests.
        uses: cypress-io/github-action@v5
        
        
