name: App on Tugboat Cypress on Testery
# See: https://docs.testery.io/integrations/ci-cd-integration-guide/github-actions
run-name: ${{ github.actor }} is triggering a Tugboat preview that will trigger Testery.

on: 
  push:
    paths:
      - .github/workflows/tugboat-preview-testery.yml
  workflow_dispatch:    
  
env:
  pantheon_site_name: 'performant-labs'
  tugboat_repo_id: "63fe5557d5af549afd35a86a"
  
jobs:
  Run-Testery-On-Tugboat-Preview:
    name: Trigger Tugboat Preview that triggers Testery.
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "For site $pantheon_site_name.$pantheon_env."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
              
      - name: Install Tugboat and jq.
        run: |
          curl -O https://dashboard.tugboatqa.com/cli/linux/tugboat.tar.gz
          tar -zxf tugboat.tar.gz
          # sudo apt-get update && sudo apt-get install jq
          
      - name: Delete prior preview.
        run: |
          ./tugboat ls previews --json --api-token ${{ secrets.TUGBOAT_TOKEN }}  > previews.json
          echo "After ls previews."
          
          PREVIEW_ID=`jq '.[0].preview' previews.json`
          echo "After PREVIEW_ID."
          
          if [ ${PREVIEW_ID} != "null" ]; then 
            echo "Deleting preview ${PREVIEW_ID}."
            ./tugboat delete ${PREVIEW_ID} --api-token ${{ secrets.TUGBOAT_TOKEN }}
          fi
          echo "After if test."
          
      - name: Create the preview (this triggers Testery). 
        run: |
          RUN_DATE=`date "+%Y-%m-%d %H:%M:%S"`
          ./tugboat create preview "${{ github.run_id }}" \
            base=false repo=${{ env.TUGBOAT_REPO_ID }} label="Branch:main $DATE" output=json --api-token ${{ secrets.TUGBOAT_TOKEN }}

